spring:
  application:
    name: ws-yoke-notify
  profiles:
    active: native

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: root
      password: '{cipher}783b329dd969751a375354abdc349c452f294cbdd01f6b9f16e1e2ddea72117c'
      database: yoke

server:
  port: 8085
  
