spring:
  application:
    name: ws-yoke-notify
  profiles:
    active: native

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: root
      password: '{cipher}2d623e134f2e759eb2590530fdd958eac1de468fa94c4b18cbf23a2e34809a20'
      database: yoke

server:
  port: 8085
  
encrypt:
  keyStore: _LT_54MX2e<T)ovEZRa7J##VlEMG}Y
